CREATE DATABASE project_management_development;

USE project_management_development;

CREATE TABLE USERS(
	USER_ID INT (10) NOT NULL,
	USERNAME VARCHAR (50) NOT NULL,
	EMAIL_ID VARCHAR (50) NOT NULL,
	PASSWORD VARCHAR (50) NOT NULL,
	PRIMARY KEY ( USER_ID ),
	PRIMARY KEY ( EMAIL_ID )
);

CREATE TABLE USER_PROFILES(
	USER_ID INT (10) NOT NULL,
	EMAIL_ID VARCHAR (50) NOT NULL,
	PHONE_NUMBER INT (15) NOT NULL,
	FOREIGN KEY ( USER_ID ) REFERENCES USER(USER_ID),
	FOREIGN KEY ( EMAIL_ID ) REFERENCES USER(EMAIL_ID)
);

CREATE TABLE PROJECTS(
	PROJECT_ID INT (10) NOT NULL,
	PROJECTNAME VARCHAR (50) NOT NULL,
	OWNER VARCHAR (50) NOT NULL,
	PRIMARY KEY ( PROJECT_ID ),
	FOREIGN KEY ( OWNER ) REFERENCES USER(EMAIL_ID)
);

CREATE TABLE PROJECT_MEMBERS(
	ID INT (10) NOT NULL,
	MEMBER_ID INT (10) NOT NULL,
	PROJECT_ID INT (50) NOT NULL,
	OWNER BOOLEAN NOT NULL,
	PRIMARY KEY ( ID ),
	FOREIGN KEY ( PROJECT_ID ) REFERENCES PROJECT(PROJECT_ID)
);
